name: material_color_picker_wns
description: Material color picker with some possible customizations for Flutter apps
version: 1.0.7
homepage: https://github.com/ajumalp/material_color_picker_wns

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0-0 <3.0.0'