name: flutter_material_color_picker
description: Material color picker with some possible customizations for Flutter apps
version: 1.0.6
homepage: https://github.com/ajumalp/flutter_material_color_picker

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0-0 <3.0.0'